[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

# v1.4 (the latest tagged) does not work with ishell
[[override]]
  name = "github.com/chzyer/readline"
  revision = "f6d7a1f6fbf35bbf9beb80dc63c56a29dcfb759f"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "v1.8.23"

[[constraint]]
  name = "github.com/quorumcontrol/chaintree"
  source = "git@github.com:quorumcontrol/chaintree.git"  
  revision = "0ea4fa148371bf76de1ac733b9be7c206c026f31"

[[constraint]]
  name = "github.com/quorumcontrol/storage"
  source = "git@github.com:quorumcontrol/storage.git"
  version = "v1.1.1"

[[constraint]]
  name = "github.com/ipfs/go-cid"
  revision = "6e296c5c49ad84dc6a44af69fa1fe4e1245cd0cf"

[[constraint]]
  name = "github.com/ipfs/go-ipld-cbor"
  revision = "5a60a3a4a7ccddcc717bbac9f8e0a65dd982ad46"

[[constraint]]
  name = "github.com/ipsn/go-ipfs"
  revision = "4b3ab38e3ef37ded722bab7ee9f3c4cf69fbaeff"

[[constraint]]
  name = "github.com/dedis/kyber"
  source = "https://github.com/quorumcontrol/kyber.git"
  revision = "189774c4cc923eb3772a72eecbb50cec5eaf2610"

[[constraint]]
  name = "github.com/tinylib/msgp"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/AsynkronIT/protoactor-go"
  revision = "0d2db0f2915c63ee18832b7ed7216d80b1019bc9"