[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.0"

# v1.4 (the latest tagged) does not work with ishell
[[override]]
  name = "github.com/chzyer/readline"
  revision = "f6d7a1f6fbf35bbf9beb80dc63c56a29dcfb759f"

[[constraint]]
  name = "github.com/ethereum/go-ethereum"
  version = "v1.8.23"

[[constraint]]
  name = "github.com/quorumcontrol/chaintree"
  source = "git@github.com:quorumcontrol/chaintree.git"  
  version = "v5.1.0"

[[constraint]]
  name = "github.com/quorumcontrol/storage"
  source = "git@github.com:quorumcontrol/storage.git"
  version = "v1.1.1"

[[constraint]]
  name = "github.com/ipfs/go-ipld-cbor"
  revision = "5a60a3a4a7ccddcc717bbac9f8e0a65dd982ad46"

[[constraint]]
  name = "github.com/ipsn/go-ipfs"
  revision = "30b2b298240fb29ae96ebc1dce5c7ce6f541bf78"

[[constraint]]
  name = "github.com/dedis/kyber"
  source = "https://github.com/quorumcontrol/kyber.git"
  revision = "189774c4cc923eb3772a72eecbb50cec5eaf2610"

[[constraint]]
  name = "github.com/tinylib/msgp"
  version = "v1.1.0"

[[constraint]]
  name = "github.com/AsynkronIT/protoactor-go"
  revision = "ffaa0eb15dcbc5dc2af7998128015a887dc005c0"

[[override]]
  name = "github.com/ipfs/go-ipfs-http-client"
  source = "github.com/quorumcontrol/ipsn-go-ipfs-http-client"
  revision = "984004a746c6b66a07839f2925ed79345dd8e67f"

[[override]]
  name = "github.com/cheggaaa/pb"
  version = "v1.0.27"
