on: delete
name: Docker Tag Deletion
jobs:
  dockerDeleteTag:
    name: Docker Delete Tag
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker Login
      run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Docker Delete Tag
      uses: ./.github/actions/docker-delete-tag
