on: push
name: Docker Build & Push
jobs:
  dockerLogin:
    name: Docker Login
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: git setup
      run: scripts/ci-gitsetup.sh
    - name: Docker Login
      run: docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: Build & Push
      run: scripts/ci-dockerbuildpush.sh
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        GITHUB_REF: ${{ github.ref }}
   