name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: git setup
        run: scripts/ci-gitsetup.sh
      - name: run tests
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          GOPATH: ~/go
        run: scripts/ci-build.sh
