name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout tupelo-go-sdk
        uses: actions/checkout@v1
      - name: git setup
        run: scripts/ci-gitsetup.sh
      - name: run tests
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: scripts/ci-build.sh
      - name: checkout tupelo master
        uses: actions/checkout@v1
        with:
          repository: quorumcontrol/tupelo
          ref: master
          fetch-depth: 1
          path: ${{ runner.workspace }}/tupelo
      - name: run integration tests w/ tupelo master
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: scripts/ci-integration-tests.sh
