name: Run tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: checkout tupelo-go-sdk
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: git setup
        run: scripts/ci-gitsetup.sh
      - name: run unit tests
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: scripts/ci-build.sh
      - name: run integration tests with tupelo signers
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: scripts/ci-integration-tests.sh
